import { Injectable } from '@angular/core';
import { AngularFirestore } from '@angular/fire/compat/firestore';
import { BehaviorSubject } from 'rxjs';
import { Question, CustomQuestionService } from './customquestion.service';

export interface Player {
  id: string; // Unique identifier for the player (generated by Firestore or another method)
  name: string;
  score: number; 
  timestamp: Date;
  lastanswertimestamp: Date;
  isCorrect: boolean;
}

export interface GameData {
  questions: Question[];
  players: Player[];
  gameState: string;
  currentQuestionIndex: number;
  roundNumber: number;
}

interface QuestionSet {
  questions: Question[];
} //Deprecated


@Injectable({
  providedIn: 'root'
})

export class GameService {

  private gameId: string ='';
  private questions: Question[] = [];
  private players: Player[] = [];
  private currentQuestionIndex: number = 0;
  private roundNumber: number = 1;
  private gameState: string = 'stopped'; 
  private timerValue: number = 30; // Default timer value
  private timerInterval: any;

  private gameStateSubject = new BehaviorSubject<string>('stopped');
  gameState$ = this.gameStateSubject.asObservable();

  private playersSubject = new BehaviorSubject<Player[]>([]);
  players$ = this.playersSubject.asObservable();

  private currentQuestionSubject = new BehaviorSubject<Question | null>(null);
  currentQuestion$ = this.currentQuestionSubject.asObservable();

  private timerSubject = new BehaviorSubject<number>(this.timerValue);
  timer$ = this.timerSubject.asObservable();

  constructor(private firestore: AngularFirestore ,private customQuestionService: CustomQuestionService) {}

  get currentGameId(): string {
    return this.gameId;
  }

  // Create a new game with a specified question set ID
  async createNewGame(questionSetId: string): Promise<void> {
    this.gameId = this.firestore.createId(); // Generate a unique game ID
    this.questions = await this.loadQuestions(questionSetId);
    this.players = [];
    this.currentQuestionIndex = 0;
    this.roundNumber = 1;

    //set game data
    const gameData: GameData = {
      questions: this.questions,
      players: this.players,
      gameState: 'waiting',
      currentQuestionIndex: this.currentQuestionIndex,
      roundNumber: this.roundNumber
    };

    await this.firestore.collection('games').doc(this.gameId).set(gameData);
    this.gameStateSubject.next('waiting');
  }
  // Join a game using the game ID
  async joinGame(gameId: string, playerName: string): Promise<string> {
    this.gameId = gameId;

    try {
      const gameDoc = await this.firestore.collection('games').doc(this.gameId).get().toPromise();

      if (gameDoc && gameDoc.exists) {
        const gameData = gameDoc.data() as GameData;

        this.questions = gameData.questions || [];
        this.players = gameData.players || [];
        this.gameState = gameData.gameState || 'stopped';
        this.currentQuestionIndex = gameData.currentQuestionIndex || 0;
        this.roundNumber = gameData.roundNumber || 1;

        const newPlayerId = this.firestore.createId();
        const newPlayer: Player = {
          id: newPlayerId,
          name: playerName,
          score: 0,
          timestamp: new Date(),
          lastanswertimestamp: new Date(),
          isCorrect: false
        };
        this.players.push(newPlayer);

        await this.updateGameState();
        return newPlayerId;
      } else {
        throw new Error(`Game with ID ${this.gameId} does not exist.`);
      }
    } catch (error) {
      console.error("Error joining the game: ", error);
      throw error;
    }
  }
  



  // Start a new round
  async startRound() {
    // If game is not started, do nothing 
    if (this.gameState !== 'stopped') return; 

    this.gameState = 'started';
    this.currentQuestionIndex = 0; 
    this.roundNumber++;

    /*// Update game state in Firestore
    await this.firestore.collection('games').doc(this.gameId).update({
      gameState: 'started',
      currentQuestionIndex: 0,
      roundNumber: this.roundNumber
    });*/

    this.gameStateSubject.next(this.gameState);
    await this.updateGameState();
  }


  // Advance to the next question 
  async nextQuestion() {
    // Check for the end of the round
    if (this.currentQuestionIndex >= this.questions.length - 1) {
      // Trigger end of round actions
      this.gameState = 'stopped';
      this.currentQuestionIndex = 0;
      this.gameStateSubject.next(this.gameState);
      this.stopGame();
      await this.updateGameState();
      return;
    } else{

    
    this.currentQuestionIndex++;
    this.currentQuestionSubject.next(this.questions[this.currentQuestionIndex]);
    this.startTimer();
    await this.updateGameState();
    }
    
  }

  // Handle player answers
  async submitAnswer(playerId: string, answer: string) {
    const currentQuestion = this.questions[this.currentQuestionIndex];
    const isCorrect = currentQuestion.answer === answer;

    this.players = this.players.map(p => {
      if (p.id === playerId) {
        return {
          ...p,
          score: isCorrect ? p.score + 1 : p.score,
          lastanswertimestamp: new Date(),
          isCorrect: isCorrect
        };
      }
      return p;
    });

    this.playersSubject.next(this.players);
    await this.updateGameState();
    /*// Update player score in Firestore
    await this.firestore.collection('games').doc(this.gameId).update({
      players: this.players
    });*/
  }

  // Pause the game
  async pauseGame() {
    this.gameState = 'paused';
    this.gameStateSubject.next(this.gameState);
    await this.updateGameState();
    this.stopTimer();
  }
  getPlayerIdByGameId(gameId: string): Promise<string | null> {
    return new Promise(resolve => {
      const player = this.players.find(p => p.id === gameId);
      if (player) {
        resolve(player.id);
      } else {
        resolve(null);
      }
    });
  }

  getPlayerById(playerId: string): Player | undefined {
    return this.players.find(p => p.id === playerId);
  }


  async isValidGame(gameId: string): Promise<boolean> {
    try {
      const gameDoc = await this.firestore.collection('games').doc(gameId).get().toPromise();
      return gameDoc?.exists ?? false;
    } catch (error) {
      console.error('Error checking game validity:', error);
      return false;
    }
  }
  // Resume the game
  async resumeGame() {
    this.gameState = 'started';
    this.gameStateSubject.next(this.gameState);
    await this.updateGameState();
  }

  // Get current question
  getCurrentQuestion(): Question {
    return this.questions[this.currentQuestionIndex];
  }

  // Get current round number
  getCurrentRound(): number {
    return this.roundNumber;
  }

  // Get all players 
  getPlayers(): Player[] {
    return this.players;
  }

  public getGameState(): string {
    return this.gameState;
  }

  // Load questions from Firestore (you've already implemented this in CustomQuestionService)
  private async loadQuestions(questionSetId: string): Promise<Question[]> {
    const docRef = this.firestore.collection('questionSets').doc(questionSetId);
    const docSnapshot = await docRef.get().toPromise();

    if (docSnapshot && docSnapshot.exists) {
      const data = docSnapshot.data() as { questions: Question[] };
      return data.questions || [];
    } else {
      throw new Error(`Question set with ID ${questionSetId} not found`);
    }
  }
  async startGame(): Promise<void> {
    this.gameState = "started";
    this.gameStateSubject.next(this.gameState);
    this.currentQuestionSubject.next(this.questions[0]);
    await this.updateGameState();
    this.startTimer(); // Start the timer when the game starts
  }
  public stopGame(): void {
    this.gameState = 'stopped';
    this.gameStateSubject.next(this.gameState);
    this.stopTimer();
  }

  async endGame(): Promise<void> {
    // Clean up game state, calculate final scores, etc.
    this.gameStateSubject.next('ended');
    await this.updateGameState();
  }

  // Method to add a player to the game
  async addPlayer(player: Player): Promise<void> {
    const currentPlayers = this.playersSubject.value;
    currentPlayers.push(player);
    this.playersSubject.next(currentPlayers);
    // Update Firestore with new player
  }

  private async updateGameState(): Promise<void> {
    const gameData: GameData = {
      questions: this.questions,
      players: this.players,
      gameState: this.gameStateSubject.value,
      currentQuestionIndex: this.currentQuestionIndex,
      roundNumber: this.roundNumber
    };

    await this.firestore.collection('games').doc(this.gameId).update(gameData);
  }

  private startTimer() {
    this.stopTimer();
    this.timerValue = 30; // Reset timer value
    this.timerSubject.next(this.timerValue);

    this.timerInterval = setInterval(() => {
      this.timerValue--;
      this.timerSubject.next(this.timerValue);
      if (this.timerValue <= 0) {
        this.stopTimer();
        this.nextQuestion();
      }
    }, 1000);
  }

  private stopTimer() {
    if (this.timerInterval) {
      clearInterval(this.timerInterval);
    }
  } //Make sure these two are called
}
